### ISSUE TITLE
Docker Swarm/K8s - NFS

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorIdentity.k8s#13]
- [ ] - 1 Add GlusterFS to Vagrant-Swarm

Use any Shared Volume Driver that will work

#### Directory
https://github.com/stuartshay/NavigatorIdentity.k8s/tree/master/vagrant-swarm

#### /provision/node.sh
https://github.com/stuartshay/NavigatorIdentity.k8s/blob/master/vagrant-swarm/provision/node.sh#L51

#### Links

http://embaby.com/blog/using-glusterfs-docker-swarm-cluster/
https://github.com/carmstrong/multinode-glusterfs-vagrant

- [ ] - 2 Add GlusterFS to K8s Cluster 

Use Any Storage Driver that works best 

Links
https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by dmitryint** [comment]
We are already using the EFS volumes for the Kubernetes cluster, so I suggest using the NFS for Vagrant too.

**Comment by stuartshay** [comment]
I don't think this works, 

Want to have the Postrgres on a Worker (Can move to container to different workers) and able to attach the volume

Is it also possible to that volume can be mounted outside of Vagrant so i can access in Windows

![capture](https://user-images.githubusercontent.com/887805/39965526-cf2ea338-5668-11e8-8347-0431d6ca4341.PNG)

**Comment by dmitryint** [comment]
To do this you need to change the constraints there: https://github.com/stuartshay/NavigatorIdentity.k8s/pull/14/files#diff-502a544e70b976233b5d06c94792f5acR17

>Is it also possible to that volume can be mounted outside of Vagrant so i can access in Windows
Yes, it is possible, only the manager should be accessible from the windows host.

**Comment by stuartshay** [comment]
I added a ```provision/nfs.sh``` which contains the NFS Mounts & the NFS Sync Folder in the Vagrant File

When I create the Postgres example, getting the following permission error

```
starting  container failed: error while mounting volume  '/var/lib/docker/volumes/nfs_postgres-data/_data': error while mounting  volume with options: type='nfs' device=':/volumes/postgres-data'  o='nfsvers=4,addr=192.168.10.2,nolock,soft,rw': connection refused
--
Image | postgres:alpine
Slot | 1
Created | 2018-05-14 05:34:17
Container ID | 08ffce41f27684a82815448912c8f02ed43ae61167d8fd1f1199f78d9a5fd752
 


```

**Comment by dmitryint** [comment]
Can you try this again without using synced folders on the manager? https://github.com/stuartshay/NavigatorIdentity.k8s/blob/master/vagrant-swarm/Vagrantfile#L59

**Comment by stuartshay** [comment]
Yes, it works without the Sync Folder, 

Missing something with the Vagrant Sync Folder Configuration
https://www.vagrantup.com/docs/synced-folders/nfs.html

**Comment by stuartshay** [comment]
This is good enough for now, just want to map the required mount points for the docker images, can always go into the VM and copy the files to the  Vagrant share
